services:
  postgres:
    image: postgres:17-alpine
    container_name: airflow_postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    networks:
      - transit-net

  airflow:
    image: apache/airflow:2.8.1-python3.10
    container_name: airflow
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/dags
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__WEBSERVER__WEB_SERVER_WORKER_TIMEOUT: 360
      PYTHONPATH: /opt/airflow/src
    env_file:
      - .env
    volumes:
      - ./scripts:/scripts
      - ./dags:/opt/airflow/dags
      - ./src:/opt/airflow/src
      - ./data:/opt/airflow/data
      - ./config:/opt/airflow/config
      - ./requirements.txt:/requirements.txt
    ports:
      - "8080:8080"
    command: bash /scripts/start_airflow.sh
    networks:
      - transit-net

  python-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python_dev
    volumes:
      - .:/app
    working_dir: /app
    tty: true
    networks:
      - transit-net

volumes:
  postgres-db-volume:

networks:
  transit-net:
